### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by rbhatt1999** [rbhatt1999/recipe_app#12]
# Hello Code Reviewer 👋 👋 
![image](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYWRiNjU1OWY5NjZmYzZjNGU1OGFlODgyYmE2YzI2NTU0MzBiYjA3YSZjdD1n/SbKNFpFZEumGTkgPgA/giphy.gif)

### Team member

- Member 1 - @codehass 
- Member 2 - @rbhatt1999

**Comment by Olamarx** [comment]
> # Hello Code Reviewer 👋 👋
> ![image](https://camo.githubusercontent.com/bac1523ee4581fb346a2ffe3a03ecc3e482a53844c509f14fc0b088affca180d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a4578595752694e6a55314f5759354e6a5a6d597a5a6a4e4755314f47466c4f446779596d4532597a49324e5455304d7a4269596a413359535a6a6444316e2f53624b4e4670465a45756d47546b675067412f67697068792e676966)
> 
> ## Please find the link for project below:
> ### [Link for Projects](https://github.com/rbhatt1999/recipe_app/projects/1)
> ### Team member
> * Member 1 - @codehass
> * Member 2 - @rbhatt1999

Hi Team, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>
## Highlights
- Kanban board ✔️
- Equal distribution ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I will implore you to add the login page to the project tasks as it is missing there as shown in the image below.
![image](https://user-images.githubusercontent.com/86200356/232436768-fb15a5ca-b769-4246-809f-ee36406be5c9.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job following the instructions of the previous CR!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
